### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by metikulos** [harmonizerblinks/ussd-builder#2]
Failed to get route: TypeError: Cannot read properties of undefined (reading 'next')
    at UssdMenu.resolveRoute (/home/francis/Documents/Projects/nodejs/gcaccra-ussd/node_modules/ussd-builder/lib/ussd-menu.js:139:20)
    at /home/francis/Documents/Projects/nodejs/gcaccra-ussd/node_modules/ussd-builder/lib/ussd-menu.js:572:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
/home/francis/Documents/Projects/nodejs/gcaccra-ussd/node_modules/ussd-builder/lib/ussd-menu.js:580
                return this.emit('error', new Error(err));
                                          ^
How

**Comment by harmonizerblinks** [comment]
kindly share a screenshot of your code
